blank_issues_enabled: false

contact_links:
  - name: 💬 Discussões (Dúvidas e Ideias)
    url: https://github.com/domflamingo2/simulado-prf/discussions
    about: Use esta área para tirar dúvidas, sugerir ideias ou conversar sobre o projeto.

  - name: 📖 Documentação / Guia do Projeto
    url: https://github.com/domflamingo2/simulado-prf/wiki
    about: Consulte a documentação antes de abrir uma issue.

  - name: 🚀 Roadmap do Projeto
    url: https://github.com/domflamingo2/simulado-prf/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement
    about: Veja funcionalidades planejadas e em desenvolvimento.

  - name: 🐛 Problemas já reportados
    url: https://github.com/domflamingo2/simulado-prf/issues?q=is%3Aissue+is%3Aopen+label%3Abug
    about: Verifique se o problema já foi reportado antes de criar uma nova issue.
